1. troubleshooting-required-status-checks 2. add debug info

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -189,7 +189,11 @@ jobs:
           echo '--------Cases only passed in base----------'
           uniq -u cmp.txt
           if [ "$(uniq -u cmp.txt | wc -l)" -gt 0 ]; then echo 'Some cases passed in base but failed in head. Pls check head version'; exit 3; fi
-          if [ "$( cat ./head-log/run.log | grep "panic runtime error:" | wc -l )" -gt "$( cat ./base-log/run.log | grep "panic runtime error:" | wc -l )" ]; then echo 'Less panic in base sha. Pls check head version'; exit 2; fi
+          echo '--------Panic in head----------'
+          cat ./head-log/run.log | grep -in 'panic runtime error:'
+          echo '--------Panic in base----------'
+          cat ./base-log/run.log | grep -in 'panic runtime error:'
+          if [ "$( cat ./head-log/run.log | grep -in 'panic runtime error:' | wc -l )" -gt "$( cat ./base-log/run.log | grep -in 'panic runtime error:' | wc -l )" ]; then echo 'Less panic in base sha. Pls check head version'; exit 2; fi
 
       - name: remove some files
         if: ${{ always() }}
@@ -209,3 +213,9 @@ jobs:
           path: |
             ${{ github.workspace }}
           retention-days: 7
+
+  lint-docs:
+    name: Lint Docs
+    runs-on: ubuntu-latest
+    steps:
+      - run: 'echo "No build required" '
