modify target branch upgrade ci and add release upgrade ci

diff --git a/.github/workflows/e2e-upgrade.yaml b/.github/workflows/e2e-upgrade.yaml
--- a/.github/workflows/e2e-upgrade.yaml
+++ b/.github/workflows/e2e-upgrade.yaml
@@ -2,18 +2,28 @@ name: MatrixOne e2e upgrade CI
 
 on:
   workflow_call:
+    inputs:
+      release-repo:
+        description: "release version"
+        type: string
+        default: "matrixorigin/matrixone"
+        required: true
+      release-version:
+        description: "release version"
+        type: string
+        default: "v1.1.2"
+        required: true
 
 jobs:
-  upgrade-ci-linux-x86:
+  upgrade-ci-target-linux-amd64:
     runs-on: ubuntu-latest
-    name: Compatibility Test on Linux/x64(LAUNCH)
-    timeout-minutes: 90
+    name: Compatibility Test With Target on Linux/x64(LAUNCH)
+    timeout-minutes: 60
 
     steps:
       - name: checkout head
         uses: actions/checkout@v3
         with:
-          fetch-depth: '3'
           path: ./head
           repository: ${{ github.event.pull_request.head.repo.full_name }}
           ref: ${{ github.event.pull_request.head.ref }}
@@ -21,10 +31,166 @@ jobs:
       - name: checkout upstream
         uses: actions/checkout@v3
         with:
-          fetch-depth: '3'
           path: ./upstream
           repository: ${{ github.event.pull_request.base.repo.full_name }}
           ref: ${{ github.event.pull_request.base.ref }}
+
+      - name: Set up Go
+        uses: ./upstream/.github/actions/setup_env
+
+      - name: Build MatrixOne for head
+        run: |
+          cd $GITHUB_WORKSPACE/head && make clean && make build
+          git rev-parse --short HEAD          
+
+      - name: Build MatrixOne for upstream
+        run: |
+          cd $GITHUB_WORKSPACE/upstream && make clean && make build          
+          git rev-parse --short HEAD
+
+      - name: Create path for execution
+        run: |
+          cd $GITHUB_WORKSPACE && mkdir workspace 
+
+      - name: Start the MO for Target Branch
+        run: |
+          cd $GITHUB_WORKSPACE/workspace
+          mv $GITHUB_WORKSPACE/upstream/etc .
+          mv $GITHUB_WORKSPACE/upstream/mo-service .
+          mv $GITHUB_WORKSPACE/upstream/optools .
+   
+          ./optools/run_bvt.sh $GITHUB_WORKSPACE/workspace launch
+
+      - name: Clone test-tool repository
+        uses: actions/checkout@v3
+        with:
+          repository: matrixorigin/mo-tester
+          path: ./mo-tester
+          ref: main
+
+      - name: Set up JDK 8 for x64
+        uses: actions/setup-java@v3
+        with:
+          java-version: '8'
+          distribution: 'adopt'
+
+      - name: Start BVT Test for Target Branch 
+        id: bvt_on_latest_main_version
+        run: |
+          export LC_ALL="C.UTF-8"
+          locale
+          cd $GITHUB_WORKSPACE/mo-tester
+          sed -i 's/  port: [0-9]*/  port: 12345/g' mo.yml
+          cat mo.yml
+          echo "============================="
+
+          ./run.sh -n -g -o -p $GITHUB_WORKSPACE/upstream/test/distributed/cases -e optimistic 2>&1
+
+      - name: Dump mo-service goroutines
+        if: ${{ always() && !cancelled() }}
+        run: |
+          max_retry=5
+          retry=0
+          while [ "$(ps -ef | grep 'mo-service' | grep -v "grep" | wc -l)" -gt 0 ]; do
+            curl http://localhost:12345/debug/pprof/goroutine\?debug=2 -o ${{ github.workspace }}/workspace/upstream-dump-stacks${retry}.log
+            pkill -9 mo-service
+            retry=$((retry+1))
+            if [ ${retry} -ge ${max_retry} ]; then
+              echo 'after retry, still cannot shutdown mo-service'
+              exit 1
+            fi
+            sleep 2
+          done
+
+      - name: Start the MO of Head Ref
+        run: |
+          cd $GITHUB_WORKSPACE/workspace
+          mv mo-service mo-service-upstream
+          mv mo-service.log upstream-mo-service.log
+          rm -rf mo-data/etl
+          rm -rf etc
+          rm -rf optools
+          # delete for clear the start finish status of mo
+          rm -rf mo-data/local/system_init_completed
+          mv $GITHUB_WORKSPACE/head/etc .
+          mv $GITHUB_WORKSPACE/head/optools .
+          mv $GITHUB_WORKSPACE/head/mo-service .
+          echo "==============cn configuration of upstram=============="
+          cat ./etc/launch/cn.toml
+          echo "==============tn configuration of upstram=============="
+          if [[ -f ./etc/launch/dn.toml ]]; then
+            cat ./etc/launch/dn.toml     
+          else 
+            cat ./etc/launch/tn.toml     
+          fi
+          ./optools/run_bvt.sh $GITHUB_WORKSPACE/workspace launch
+
+      - name: Start BVT Test for Head Branch
+        id: bvt_on_latest_head_version
+        run: |
+          export LC_ALL="C.UTF-8"
+          locale
+          cd $GITHUB_WORKSPACE/mo-tester
+          sed -i 's/  port: [0-9]*/  port: 12345/g' mo.yml
+          cat mo.yml
+          echo "============================="
+          
+          ./run.sh -n -g -o -p $GITHUB_WORKSPACE/head/test/distributed/cases -e optimistic 2>&1
+
+      - name: Dump mo-service-new goroutines
+        if: ${{ always() && !cancelled() }}
+        run: |
+          max_retry=5
+          retry=0
+          while [ "$(ps -ef | grep 'mo-service' | grep -v "grep" | wc -l)" -gt 0 ]; do
+            curl http://localhost:12345/debug/pprof/goroutine\?debug=2 -o ${{ github.workspace }}/workspace/new-dump-stacks${retry}.log
+            pkill -9 mo-service
+            retry=$((retry+1))
+            if [ ${retry} -ge ${max_retry} ]; then
+              echo 'after retry, still cannot shutdown mo-service'
+              exit 1
+            fi
+            sleep 2
+          done
+
+      - name: generate upload files
+        if: ${{ always() }}
+        continue-on-error: true
+        run: |
+          mkdir -p ${{ github.workspace }}/upload
+          rm -rf ./mo-tester/.git
+          rm -rf ./mo-tester/lib
+          mv ${{ github.workspace }}/workspace ${{ github.workspace }}/upload/
+          mv ${{ github.workspace }}/mo-tester ${{ github.workspace }}/upload/
+
+      - uses: actions/upload-artifact@v3
+        if: ${{ failure() || cancelled()}}
+        continue-on-error: true
+        with:
+          name: Compatibility-Test-Target-on-Linux-x64(LAUNCH)-reports
+          path: |
+            ${{ github.workspace }}/upload
+          retention-days: 7
+
+  upgrade-ci-release-linux-amd64:
+    runs-on: ubuntu-latest
+    name: Compatibility Test With Release on Linux/x64(LAUNCH)
+    timeout-minutes: 60
+
+    steps:
+      - name: Checkout Head
+        uses: actions/checkout@v3
+        with:
+          path: ./head
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          ref: ${{ github.event.pull_request.head.ref }}
+
+      - name: Checkout Upstream Release
+        uses: actions/checkout@v3
+        with:
+          path: ./upstream
+          repository: ${{ inputs.release-repo }}
+          ref: ${{ inputs.release-version }}
 
       - name: Set up Go
         uses: ./upstream/.github/actions/setup_env
@@ -50,16 +216,6 @@ jobs:
           mv $GITHUB_WORKSPACE/upstream/mo-service .
           mv $GITHUB_WORKSPACE/upstream/optools .
           
-          # Explicitly declare pessimistic mode
-          echo "==============cn configuration of upstram=============="
-          echo ""  >> ./etc/launch/cn.toml
-          echo '[cn.txn]' >> ./etc/launch/cn.toml
-          echo 'mode = "Pessimistic"' >> ./etc/launch/cn.toml
-          echo "==============dn configuration of upstram=============="
-          echo ""  >> ./etc/launch/tn.toml
-          echo '[dn.txn]' >> ./etc/launch/tn.toml
-          echo 'mode = "Pessimistic"' >> ./etc/launch/tn.toml
-          cat ./etc/launch/tn.toml     
           ./optools/run_bvt.sh $GITHUB_WORKSPACE/workspace launch
 
       - name: Clone test-tool repository
@@ -74,9 +230,8 @@ jobs:
         with:
           java-version: '8'
           distribution: 'adopt'
-          architecture: x64
 
-      - name: Start BVT Test for MO with the Latest Version of Main
+      - name: Start BVT Test for Release ${{ inputs.release-version }}
         id: bvt_on_latest_main_version
         run: |
           export LC_ALL="C.UTF-8"
@@ -112,8 +267,10 @@ jobs:
           rm -rf mo-data/etl
           rm -rf etc
           rm -rf optools
-          # delete for clear the start finish status of mo
+
+          # delete for clear the start finish status of mo(deprecated after pr #14607)
           rm -rf mo-data/local/system_init_completed
+
           mv $GITHUB_WORKSPACE/head/etc .
           mv $GITHUB_WORKSPACE/head/optools .
           mv $GITHUB_WORKSPACE/head/mo-service .
@@ -169,7 +326,7 @@ jobs:
         if: ${{ failure() || cancelled()}}
         continue-on-error: true
         with:
-          name: Compatibility-Test-on-Linux-x64(LAUNCH)-reports
+          name: Compatibility-Test-Release-on-Linux-x64(LAUNCH)-reports
           path: |
             ${{ github.workspace }}/upload
           retention-days: 7
