change increase mode in robot

diff --git a/.github/workflows/robot.yml b/.github/workflows/robot.yml
--- a/.github/workflows/robot.yml
+++ b/.github/workflows/robot.yml
@@ -191,8 +191,9 @@ jobs:
           go tool cover -o ${{ env.ut_html_coverage }} -html=${{ env.ut_coverage }}
           echo "ut_html_coverage finished"
           rm -rf ${{ env.raw_ut_coverage }}
-          ps aux | grep 'mo-service' | grep -v 'grep' | awk '{print $2}' | xargs kill -s SIGINT
-          while(( $(ps aux|grep 'mo-service' | grep -v 'grep' | awk '{print $2}') )); do let i++;if [ $i -eq 300 ]; then exit 1; fi; echo 'mo-service kill not finished......$i/300'; sleep 1s; done
+          ps -aux | grep 'mo-service' | grep -v 'grep' | awk '{print $2}' | xargs kill -s SIGINT
+          i=1 && while [ -n "$(ps -aux|grep 'mo-service' | grep -v 'grep' | awk '{print $2}')" ] && [ $i -le 300 ]; do echo "mo-service kill not finished......$i/300"; i=$(($i+1)); sleep 1s; done
+          if [ $i -gt 300 ]; then echo 'stop mo-service failed...'; exit 1; else echo 'stop mo-service successed...'; fi
           go tool covdata textfmt -i="$GITHUB_WORKSPACE/matrixone" -o ${{ env.raw_bvt_coverage }}
           cat ${{ env.raw_bvt_coverage }} | grep -v '${{ env.bvt_excluded_pkg }}' > ${{ env.bvt_coverage }}
           echo "bvt_coverage finished"
