modify

diff --git a/.github/workflows/ut_pr.yml b/.github/workflows/ut_pr.yml
--- a/.github/workflows/ut_pr.yml
+++ b/.github/workflows/ut_pr.yml
@@ -60,6 +60,6 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/matrixone
           echo "--------------------ut_coverage start--------------------"
-          awk -F '[ %\t]+' '{if($1=="ok"){if($5 == "[no"){print "Warning: please move/create test code file to `"$2"`";} else if($5 < 75) {print "Error: the code coverage of `"$2"` is "$5"% which is below 75%";} else {print "Output: The code coverage of `"$2"` is "$5"%, this is up to standard"}} else if($1 == "?"){print "Error: There are no test files in this path -- `"$2"`";} else if($1 == "FAIL"){print "Error: The `"$2"` failed to run the test";}}' ${{ env.raw_ut_coverage }}
+          awk -F '[ %\t]+' '{if($1=="ok"){if($5 == "[no"){print "Warning: please move/create test code file to `"$2"`"; exit 1;} else if($5 < 75) {print "Error: the code coverage of `"$2"` is "$5"% which is below 75%"; exit 1;} else {print "Output: The code coverage of `"$2"` is "$5"%, this is up to standard"}} else if($1 == "?"){print "Error: There are no test files in this path -- `"$2"`"; exit 1;} else if($1 == "FAIL"){print "Error: The `"$2"` failed to run the test"; exit 1;}}' ${{ env.raw_ut_coverage }}
           rm -rf ${{ env.raw_ut_coverage }} ${{ env.ut_report }}
           echo "--------------------ut_coverage finished--------------------"
